const ACTIONS = {
	INSERT_PLAYLIST: Symbol('INSERT_PLAYLIST'),
	SHOW_LOADER: Symbol('SHOW_LOADER'),
	HIDE_LOADER: Symbol('HIDE_LOADER'),
	INSERT_CATEGORIES: Symbol('INSERT_CATEGORIES'),
	CLEAR_PLAYLISTS: Symbol('CLEAR_PLAYLISTS'),
	SHOW_ERROR: Symbol('SHOW_ERROR'),
	SAVE_TRACKS: Symbol('SAVE_TRACKS'),
	CLEAR_TRACKS: Symbol('CLEAR_TRACKS'),
	SET_PLAYING_TRACK: Symbol('SET_PLAYING_TRACK'),
	SET_PLAYING_TRACKS_LIST: Symbol('SET_PLAYING_TRACKS_LIST'),
	SET_PLAYLIST_ID: Symbol('SET_PLAYLIST_ID'),
	PLAY: Symbol('PLAY'),
	PAUSE: Symbol('PAUSE'),
	SET_PREV_AVAILABLE: Symbol('SET_PREV_AVAILABLE'),
	SET_NEXT_AVAILABLE: Symbol('SET_NEXT_AVAILABLE')
};

export default ACTIONS;
