const ACTIONS = {
	INSERT_PLAYLIST: Symbol('INSERT_PLAYLIST'),
	SHOW_LOADER: Symbol('SHOW_LOADER'),
	HIDE_LOADER: Symbol('HIDE_LOADER'),
	INSERT_CATEGORIES: Symbol('INSERT_CATEGORIES'),
	CLEAR_PLAYLISTS: Symbol('CLEAR_PLAYLISTS')
};

export default ACTIONS;
